# Generated by Django 3.1.3 on 2022-10-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_courier_paypal_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='fcm_token',
            field=models.TextField(blank=True),
        ),
    ]
